### ISSUE TITLE
Infinite ocean sometimes stop working

### ISSUE THREAD

**Issue by matheusgrieger** [UE4-OceanProject/OceanProject#86] opened 2018-08-15 14:31 UTC
The infinite ocean stops working from time to time, and the water becomes a circle. It happens randomly and only in my co-worker computer. The settings are exactly the same as with mine, and yet it doesn't work.

![image](https://user-images.githubusercontent.com/6992464/44153479-be903e82-a07e-11e8-9acc-22799d7cd677.png)

How can this be solved?

**Comment by NilsonFLima** [comment] 2018-08-15 14:35
This is something weird... we don't handle a circle mesh for the infinite ocean... I think that your skybox is culling the ocean. Check the scale of both skyboxes (which is fact are spheres) and match both scale or just make them bigger.

**Comment by matheusgrieger** [comment] 2018-08-16 14:21
Hello and thanks for your quick answer! No, the sky or its spheres are not the issue. The project is currently in an SVN, and we are on the same revision. It works just fine on my machine, but not in my colleague machine.

We've tried fiddling with all scales, both BP_Skydome and its two inherited spheres.

**Comment by NilsonFLima** [comment] 2018-08-16 14:25
How much differ the hardware between both machines? Is there enough GPU RAM on the machine with issue? Just a thought...

**Comment by matheusgrieger** [comment] 2018-08-16 17:05
Both hardwares are very different, yes, but both have enough VRAM. It was working as expected, and then suddenly, after opening UE4, it wasn't...

**Comment by NilsonFLima** [comment] 2018-08-16 17:08
OK, I will leave the issue opened, but please specify which is the engine release you are into. Hopefully when I am back from trip I will check this to see how can I break it to reproduce on my end.

**Comment by matheusgrieger** [comment] 2018-08-16 17:15
We are running Unreal Engine 4.19.2, with World Composition enabled. If you need any more details, just let me know.
And thanks in advance! :smile:

**Comment by matheusgrieger** [comment] 2018-08-20 20:35
@NilsonFLima noticed that it only happens in the editor. If I play (or simulate) the game, apparently this behavior is fixed. Yet it is still annoying to have to move the water around when editing the map...

**Comment by NilsonFLima** [comment] 2018-08-20 20:38
Matheus, notice that UE 4.19 has a huge memory leak issue which happens in editor and in packaged games, the more the editor stay opened the more memory is consumed. It might be the cause, since this does not happen in 4.18 and 4.20. UE 4.19 is not recommended as target for production Im afraid, since 4.20 is out no other fixes will be released for it.

**Comment by matheusgrieger** [comment] 2018-08-21 11:34
Oh, really?.. Didn't know that, thanks for letting me know! As soon as there is a 4.20 release of the Ocean Project, I'll see about changing my game to 4.20! Thanks for the tip :smile:

**Comment by NilsonFLima** [comment] 2018-08-21 11:37
As reference of this particular issue (there are others) follow the thread link and ways to try to workaround it (I was not successfull thou): https://forums.unrealengine.com/unreal-engine/feedback-for-epic/1457519-4-19-4-20-editor-packaged-games-have-hangs-hiccups-constantly

The current 4.19 project works in 4.20, you just need to recompile it.

**Comment by matheusgrieger** [comment] 2018-08-21 12:06
I'll give it a read, thanks again!

And, since I'm nowhere even close to knowing how to recompile this project (zero knowledge of C++), I will be on hold for that. Until then, there is some time before my game will be ready, so it's not really a problem to keep using 4.19.

**Comment by EvoPulseGaming** [comment] 2020-07-28 22:12
Over the last two years, I have never seen another issue about this. Closing

**Comment by script526** [comment] 2020-07-29 02:09
I had this issue about 6-8 months ago but I though that was intended to be so =)

**Comment by EvoPulseGaming** [comment] 2020-07-29 02:09
I'll reopen

**Comment by EvoPulseGaming** [comment] 2020-07-29 02:10
I need people with this issue to test on latest. You want the latest anyways, major improvements visually and FPS wise xD

**Comment by script526** [comment] 2020-07-29 02:10
Totally up to you, I'm not insisting. Not sure how to reproduce it.

**Comment by EvoPulseGaming** [comment] 2020-07-29 02:12
Okay, then I will re-close this. So many fixes have been done, that this may no longer be an issue. Plus all the engine updates.

**Closed as completed by EvoPulseGaming** 2020-07-29 02:12 UTC
