### ISSUE TITLE
Launch and compile issues during new releases

### ISSUE THREAD

**Issue by P1llus** [UE4-OceanProject/OceanProject#72] opened 2018-03-22 15:40 UTC
Hey!

In issue #55 there is a specific error that happens for OceanProject.dll and OceanPlugin.dll for new versions.

This issue is now back on 4.19.

Is there a specific way to resolve this? If someone could tell me the steps i am more than happy enough to do these and send off a PR for it.

EDIT: saying that, i still get the issue in #55 on 4.18.3 as well, which was supposed to be fixed, so i must be doing something wrong.

All i am trying to do is import the project directly with the uproject file.

**Comment by TheZoc** [comment] 2018-03-22 20:07
Hello @P1llus,

Apparently this happened due to a local change that wasn't committed. I'll fix this right now :)

**Comment by TheZoc** [comment] 2018-03-22 20:11
This should be fixed on b04d430 :)

**Comment by TheZoc** [comment] 2018-03-22 20:12
@P1llus This should be fixed on b04d430. Please, let me know if it works :)

**Comment by P1llus** [comment] 2018-03-22 21:50
That now works again yeah, so feel free to close the issue :) thanks for the commit. Do you mind explaining it before you close it? as i feel the bug might come up again? :)

**Comment by TheZoc** [comment] 2018-03-23 04:50
This one was caused by a "uman herror" 😛 
The while the DLL was compiled to match UE4.19, the project file was pointing to UE4.18, thus, this error was happening. If you were only using the plugin, you wouldn't see this error :)

**Closed as completed by TheZoc** 2018-03-23 04:50 UTC
Labels: Bug

**Comment by dotcamdev** [comment] 2018-05-09 02:04
Just a quick follow up, @P1llus the error between versions you are referring to (aside from this one) is not something we can fix. The plugin is C++ based and needs to be compiled to ensure compatibility with each new major update to the engine (4.18, 4.19, 4.20 etc) and is something Epic requires, so it is outside of our control. We will do our best to update and post it here as quickly as possible whenever a new version is released.

Unless there is a great new feature available this project could make use of, updating for Preview builds of the engine usually won't be available.

Thanks!
