### ISSUE TITLE
UE 4.18 - Failed to load

### ISSUE THREAD

**Issue by JulianMined** [UE4-OceanProject/OceanProject#49] opened 2017-10-26 16:26 UTC
Hello,
i can't load the plugin "Missing import: UE4Editor-ApexDestruction.dll"

**Comment by ZORN8496** [comment] 2017-10-27 01:08
Some issus， but different message

Plugin 'OceanPlugin' failed to load because module 'OceanPlugin' could not be loaded. 
There may be an operating system error or the module may not be properly set up.

**Comment by ibrews** [comment] 2017-10-27 03:00
for me it says "the following modules are missing or built with a different engine version: 

UE4Editor-OceanProject.dll
UE4Editor-OceanPlugin.dll

Would you like to rebuild them now?

And then if I say 'yes', it says "OceanProject could not be compiled. Try rebuilding from source manually."

**Comment by TheZoc** [comment] 2017-10-27 04:14
Epic changed how ApexDestruction works in the engine (it's now a separate plugin).

I've added it as a plugin dependency on 6e54a16. It works here, but I"m not sure yet if it will work on every system. Can you, please, test and report back?

Thank you very much!

**Comment by ibrews** [comment] 2017-10-27 05:09
Hi TheZoc -- I'm still getting the same error as I was. The 4.17 version worked fine for me. 

I haven't seen the ApexDestruction error that others have mentioned.

**Comment by TheZoc** [comment] 2017-10-27 05:55
Hello @ibrews,

I think that's related to Visual Studio. Those binaries were compiled with Visual Studio Community 2017 v15.4.1.
(The 4.17 binaries were probably compiled with a previous version of VS2017 too)

Which version of Visual Studio are you using?

**Comment by ibrews** [comment] 2017-10-27 16:00
Hi @TheZoc -- I have Visual Studio Community 2017 15.2 

I will try upgrading to 15.4.1

I've been able to build with 4.18, including with custom plugins-- strange the OceanPlugin is getting upset about those two dlls.

**Comment by ibrews** [comment] 2017-10-28 18:51
I can confirm that upgrading from VS Community 2017 15.2 to 15.4.1 allowed for successful rebuilding of the two problem dlls, and everything is working fine now. Thanks!

**Comment by TheZoc** [comment] 2017-10-31 22:55
@ibrews Glad to hear that everything is working fine! 😄 

@ZORN8496 @JulianMined Are you still having any issue?

**Comment by JulianMined** [comment] 2017-10-31 23:11
No, it's working - thank you 😊

**Comment by TheZoc** [comment] 2017-11-01 01:35
If anything else fails, please, let me know! 😁 

I'll close this issue.

**Closed as completed by TheZoc** 2017-11-01 01:35 UTC

**Comment by RH-Adv1c3** [comment] 2017-11-03 15:37
Hello,

I had the same issue @ibrews ,
I got a popup saying that I was missing the two dll's or that they are compiled with a different engine version.
Here's how I solved it:
1. Install the Windows v8.1 SDK (this is just the sdk not windows itself)
          Link: https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk
2. Run cmd with this command:
         "(Your drive letter):/Program Files/Epic Games/UE_4.18/Engine/Binaries/DotNET/UnrealBuildTool.exe" OceanProject Development Win64 -project="(drive letter):/(User Profile)/Documents/Unreal Projects/(Project)/OceanProject.uproject" -editorrecompile -progress"
3. Wait for cmd to finish.
4. Startup the project (I have copied all the files from the github folder OceanProject-Master to my own created project then running the unreal project .exe that you have copied from the github project folder) I have run it with engine version 4.18. In my case it needs to compile some shaders, but after that no problems acure as far as I have tested it when there are problems I will post a new command with the fix for it.

Hope this helps for people that are still looking for a solution.

**Comment by TheZoc** [comment] 2017-11-03 20:31
Hello @DamianKnappers :)

I'm glad you were able to solve this issue.
Did you need to upgrade Visual Studio to the latest version too?

Thank you for your support!

**Comment by samby707** [comment] 2018-12-20 09:06
> Hello,
> 
> I had the same issue @ibrews ,
> I got a popup saying that I was missing the two dll's or that they are compiled with a different engine version.
> Here's how I solved it:
> 
> 1. Install the Windows v8.1 SDK (this is just the sdk not windows itself)
>    Link: https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk
> 2. Run cmd with this command:
>    "(Your drive letter):/Program Files/Epic Games/UE_4.18/Engine/Binaries/DotNET/UnrealBuildTool.exe" OceanProject Development Win64 -project="(drive letter):/(User Profile)/Documents/Unreal Projects/(Project)/OceanProject.uproject" -editorrecompile -progress"
> 3. Wait for cmd to finish.
> 4. Startup the project (I have copied all the files from the github folder OceanProject-Master to my own created project then running the unreal project .exe that you have copied from the github project folder) I have run it with engine version 4.18. In my case it needs to compile some shaders, but after that no problems acure as far as I have tested it when there are problems I will post a new command with the fix for it.
> 
> Hope this helps for people that are still looking for a solution.

I tried this for the landscape project for which they have tutorial.
i get the following errors.
Performing full C++ include scan (building a new target)
@progress push 5%
@progress 'Generating code...' 0%
@progress 'Generating code...' 33%
Parsing headers for LandscapeSampProjectEditor
  Running UnrealHeaderTool "C:\Users\HarmanX\Documents\Unreal Projects\LandscapeSampProject\LandscapeSampProject.uproject" "C:\Users\HarmanX\Documents\Unreal Projects\LandscapeSampProject\Intermediate\Build\Win64\LandscapeSampProjectEditor\Development\LandscapeSampProjectEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(313) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(333) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(350) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(371) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(384) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(400) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(413) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(435) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(457) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(478) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(489) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(503) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(518) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(536) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(558) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(580) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(598) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(635) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(664) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(941) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
D:/Sambuddha/AirSim/Unreal_Engine_Win/UE_4.18/Engine/Source/Runtime/CoreUObject/Public/UObject/NoExportTypes.h(950) : LogCompile: Error: Immutable is being phased out in favor of SerializeNative, and is only legal on the mirror structs declared in UObject
UnrealHeaderTool failed for target 'LandscapeSampProjectEditor' (platform: Win64, module info: C:\Users\HarmanX\Documents\Unreal Projects\LandscapeSampProject\Intermediate\Build\Win64\LandscapeSampProjectEditor\Development\LandscapeSampProjectEditor.uhtmanifest).
