### ISSUE TITLE
Problem with AdvancedBuoyancyComponent.cpp	

### ISSUE THREAD

**Issue by tomaszzackiewicz** [UE4-OceanProject/OceanProject#70] opened 2018-03-15 11:32 UTC
Hi, I have just upgraded my UE 4.18 project with the OceanProject to UE 4.19 and I got the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0393	pointer to incomplete class type is not allowed	ZSFS_I	d:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	218	
Error (active)	E0393	pointer to incomplete class type is not allowed	ZSFS_I	d:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	219	
Error (active)	E0135	class "FStaticMeshLODResources" has no member "PositionVertexBuffer"	ZSFS_I	d:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	223	
Error (active)	E0135	class "FStaticMeshLODResources" has no member "PositionVertexBuffer"	ZSFS_I	d:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	225	
Error (active)	E0135	class "FStaticMeshLODResources" has no member "PositionVertexBuffer"	ZSFS_I	d:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	255	
Error (active)	E0135	class "FStaticMeshLODResources" has no member "PositionVertexBuffer"	ZSFS_I	d:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	258	
Error	C2039	'PositionVertexBuffer': is not a member of 'FStaticMeshLODResources'	ZSFS_I	D:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	223	
Error	C2228	left of '.VertexBufferRHI' must have class/struct/union	ZSFS_I	D:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	223	
Error	C2227	left of '->GetSize' must point to class/struct/union/generic type	ZSFS_I	D:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	223	
Error	C2039	'PositionVertexBuffer': is not a member of 'FStaticMeshLODResources'	ZSFS_I	D:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	240	
Error	C2661	'UAdvancedBuoyancyComponent::PopulateTrianglesFromStaticMesh::EURCMacro_GetMyBuffers::EURCMacro_GetMyBuffers': no overloaded function takes 3 arguments	ZSFS_I	D:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	240	
Error	C2039	'PositionVertexBuffer': is not a member of 'FStaticMeshLODResources'	ZSFS_I	D:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	255	
Error	C2039	'PositionVertexBuffer': is not a member of 'FStaticMeshLODResources'	ZSFS_I	D:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	258	
Error	C2228	left of '.GetStride' must have class/struct/union	ZSFS_I	D:\ZSFS_I\Plugins\OceanPlugin\Source\OceanPlugin\Private\AdvancedBuoyancyComponent\AdvancedBuoyancyComponent.cpp	258	
Error	C2664	'void TBaseDynamicMulticastDelegate<FWeakObjectPtr,void,const TArray<AActor *,FDefaultAllocator> &>::__Internal_AddDynamic<AZSFSEnemy1ConBase>(UserClass *,void (__cdecl AZSFSEnemy1ConBase::* )(const TArray<AActor *,FDefaultAllocator> &),FName)': cannot convert argument 2 from 'void (__cdecl AZSFSEnemy1ConBase::* )(TArray<AActor *,FDefaultAllocator>)' to 'void (__cdecl AZSFSEnemy1ConBase::* )(const TArray<AActor *,FDefaultAllocator> &)'	ZSFS_I	D:\ZSFS_I\Source\ZSFS_I\ZSFSEnemy1ConBase.cpp	44	
Error	C2664	'void TBaseDynamicMulticastDelegate<FWeakObjectPtr,void,const TArray<AActor *,FDefaultAllocator> &>::__Internal_AddDynamic<ABHController>(UserClass *,void (__cdecl ABHController::* )(const TArray<AActor *,FDefaultAllocator> &),FName)': cannot convert argument 2 from 'void (__cdecl ABHController::* )(TArray<AActor *,FDefaultAllocator>)' to 'void (__cdecl ABHController::* )(const TArray<AActor *,FDefaultAllocator> &)'	ZSFS_I	D:\ZSFS_I\Source\ZSFS_I\BHController.cpp	40	
Error	C2664	'void TBaseDynamicMulticastDelegate<FWeakObjectPtr,void,const TArray<AActor *,FDefaultAllocator> &>::__Internal_AddDynamic<ALav25ConBase>(UserClass *,void (__cdecl ALav25ConBase::* )(const TArray<AActor *,FDefaultAllocator> &),FName)': cannot convert argument 2 from 'void (__cdecl ALav25ConBase::* )(TArray<AActor *,FDefaultAllocator>)' to 'void (__cdecl ALav25ConBase::* )(const TArray<AActor *,FDefaultAllocator> &)'	ZSFS_I	D:\ZSFS_I\Source\ZSFS_I\Lav25ConBase.cpp	37	
Error	C2664	'void TBaseDynamicMulticastDelegate<FWeakObjectPtr,void,const TArray<AActor *,FDefaultAllocator> &>::__Internal_AddDynamic<AMainHeroConBase>(UserClass *,void (__cdecl AMainHeroConBase::* )(const TArray<AActor *,FDefaultAllocator> &),FName)': cannot convert argument 2 from 'void (__cdecl AMainHeroConBase::* )(TArray<AActor *,FDefaultAllocator>)' to 'void (__cdecl AMainHeroConBase::* )(const TArray<AActor *,FDefaultAllocator> &)'	ZSFS_I	D:\ZSFS_I\Source\ZSFS_I\MainHeroConBase.cpp	44	
Error		UBT ERROR: Failed to produce item: D:\ZSFS_I\Plugins\OceanPlugin\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-OceanPlugin.lib	ZSFS_I	D:\ZSFS_I\Intermediate\ProjectFiles\UnrealBuildTool	1	
Error	MSB3075	The command ""C:\Program Files\Epic Games\UE_4.19\Engine\Build\BatchFiles\Build.bat" ZSFS_IEditor Win64 Development "D:\ZSFS_I\ZSFS_I.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.	ZSFS_I	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets	41

**Comment by TheZoc** [comment] 2018-03-15 23:05
Thsi is duplicate of #60. Should be fixed soon :)

**Closed as completed by TheZoc** 2018-03-15 23:05 UTC
Labels: Duplicate
