### ISSUE TITLE
Editor Hang Editing BP_ManOfWar

### ISSUE THREAD

**Issue by JasonWeise** [UE4-OceanProject/OceanProject#85] opened 2018-07-31 21:09 UTC
Hi Team

There seems to be an issue with the UE4 editor hanging when editing and compiling the ManOfWar Blueprint (BP_ManOfWar).

I am using the most recent OceanProject commit and UE 4.20.1 and have confirmed the issue on two different machines.
To reproduce, open BP_ManOfWar make *any* change and click compile and the editor just hangs completely.

NOTE: Checking Task Manager in Windows appears to show there is a memory leak somewhere as editor memory usage climbs indefinitely and consumed my 32GB Ram in about 45 minutes if I leave the editor in the hung state. This seems to only occur if I compile the ManOfWar blueprint.

I have used and edited the other blueprints and all look ok except for ManOfWar and I really need to use this one for a demo I am making and this issue is a blocker.

Is anyone else able to confirm this issue in 4.20.1 or know a work around (or the cause)

Thanks in advance,

**Comment by NilsonFLima** [comment] 2018-07-31 23:59
Hi Jason,

I have just checked the original project at GitHub and opened it with 4.20 it went fine, including making changes in the BP_ManOfWar, nothing hanged or leaked, but... there are some issues with 4.20 related with memory leaks because of a component from NVidia called Aftermath, which must be disabled when it occurs. There is a report in the forums on how to do it.

If you have migrated the original project into your own, there is an issue that would trigger some errors (but not memory leaks at least) which are related to the Physical Surfaces not being set (happens if you don't copy the DefaultEngine.ini, but you can edit in your project and add the following lines inside the [/Script/Engine.PhysicsSettings] section:

+PhysicalSurfaces=(Type=SurfaceType1,Name="Ice")
+PhysicalSurfaces=(Type=SurfaceType2,Name="Wood")
+PhysicalSurfaces=(Type=SurfaceType3,Name="Metal")

Hope that helps!

**Comment by JasonWeise** [comment] 2018-08-01 02:09
Hi @NilsonFLima 
Thanks for the speedy response.
I might just re-download the current master branch and try again but I didn't migrate the project at all, I downloaded the repo, updated the project to 4.20 and opened in editor.
Only thing from there was adding some static meshes as content and starting to have a play.

I will re-download and try again with a whole new project and see how that goes.

Once again thanks for your help.

**Comment by NilsonFLima** [comment] 2018-08-01 11:13
I have made some more experiments today, and disconnecting the BeginPlay node and hitting compile just hanged the editor. I also saw the memory starting to increase at the TaskManager. My thoughts for now is that it is related to the memory leak problem on the editor and it is just not simply related to that blueprint, since it does not have any C++ code at the plugin side, it just derives from Pawn class. I will check the procedure to disable the Aftermath component and will post here.

**Comment by JasonWeise** [comment] 2018-08-01 18:49
I've tested further and my 4.20.1 install had Aftermath disabled already via BaseEngine.ini
`r.gpucrashdebugging = False`

and the BeginPlay node is still connected, in fact, if I just open the included BP_ManOfWar blueprint and hit compile the editor freezes instantly.

**Comment by NilsonFLima** [comment] 2018-08-01 18:56
The Aftermath DLL has to be renamed too, but the freeze like you describe only happens when I disconnect the BeginPlay node and hit compile... hitting compile after disconnecting and connecting again causes no issue. Anyway, this is an issue with the editor, simply because it does not happen in previous versions and BP_ManOfWar is just an actor blueprint, there is no C++ code related to it inside the plugin.

I have found another project with Actor blueprints, with no C++ code, no plugins whatsoever, and when I disconnect some nodes and hit Compile is just crashing the editor, so.. I am still trying to figure if anyone has reported this and if not I will make a reproduction project and submit a bug sub form.

**Comment by ghost** [comment] 2018-08-01 19:09
I ran into this problem too. It used about 15.9 GB of my RAM then quieted down and just hovered at 10GB for the better part of an hour. Eventually, I got bored and killed the editor. It happened twice, only with the BP_ManOfWar.

**Comment by JasonWeise** [comment] 2018-08-01 19:11
Thanks @NilsonFLima 
I have opened a fresh copy of the master branch on 4.19.2 doing nothing other than open BP_ManOfWar and hit compile and the editor in 4.19.2 freezes as well.

I have opened other Blueprints in the project:
`BP_Boat
AdvBuoyantBoat
BP_BuoyantActor`
and hit compile and no drama at all these do not hang the editor in 4.19.2 or 4.20.1

Must be something odd with BP_ManOfWar.

**Comment by NilsonFLima** [comment] 2018-08-02 01:07
I was still doing research and there are reports of Blueprint only projects having crashes when hitting compile: https://forums.unrealengine.com/unreal-engine/announcements-and-releases/1502911-unreal-engine-4-20-released/page8  for the first two posts. There are more. I think just for the sake of reassuring they will get this issue I will try to create a small project with info that relates to the way BP_ManOfWar is built, so maybe we can get some light from the devs and when the issue will be fixed.

**Comment by JasonWeise** [comment] 2018-08-02 06:33
Thanks so much for the help @NilsonFLima 

It is definitely an annoying issue.

On another note (probably should not be in this thread), but I think I read on the UE4 Forum for this project that there is a new version coming soon with new / updated features.

Did I read this correctly and if so, do you know when it is likely to be committed?
I might wait for it to be released here if there is a new version coming soon :)

**Comment by NilsonFLima** [comment] 2018-08-02 11:07
We are making changes in a 3 person effort. We will integrate with this Gerstner waves shader another FFT waves shader (more realistic for mid ocean) totally in compute shader, there will be an add-on module for weather also in compute shader and we might streamline the project a bit, putting everything not Ocean related as an add-on, since some of them are users contribution. There is no ET yet, but we are moving into that direction.

**Comment by JasonWeise** [comment] 2018-08-02 21:04
Thanks for the update @NilsonFLima, looking forward to the new version, sound great.

It is unfortunate about the issue with Blueprints and 4.20 and hopefully Epic will find it fixed soon.
I guess in the meantime I will have to concentrate on other items.

Thanks for your help, I guess we can close this issue now.

**Closed as completed** 2018-08-02 21:21 UTC
